spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kmkemail1021@gmail.com
    password: wkkrlmvrgidndoxy
  datasource:
    hikari:
      password: '1111'
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      connection-test-query: SELECT NOW() FROM dual