spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 922405067379-s6hqmtorgvp0cibhs0t7gbvg257irbah.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: DGZfFjNzCXL8jyQarIYO
            client-secret: CS06vo6407
            client-name: Naver
            redirect-uri: http://localhost:8091/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mail:
    host: smtp.gmail.com
    port: 587
    username: kmkemail1021@gmail.com
    password: wkkrlmvrgidndoxy
  datasource:
    hikari:
      password: '1111'
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      connection-test-query: SELECT NOW() FROM dual

#scope 기본값은 email, profile, openid 인데 profile, email만 입력한 이유는  
#※ openid가 있으면 OpenId Provider로 인식하기 때문인데, 이렇게 되면 OpenId Provider인 서비스와 그렇지 않은 서비스(네이버/카카오 등)로 나눠서 각각 OAuth2Service를 만들어야 한다.